version: '3.3'
services:
  postgres:
    restart: always
    build: ./postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - POSTGRES_USER=${POSTGRES_USER:?error}
    volumes:
      - "postgres:/var/lib/postgresql/data"
  math:
    build: ./generator
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?error}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - POSTGRES_USER=${POSTGRES_USER:?error}
      - POSTGRES_HOST=${POSTGRES_HOST:?error}
      - POSTGRES_PORT=${POSTGRES_PORT:?error}
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - postgres

volumes:
    postgres: {}