env:
  browser: true
  es2021: true
  jquery: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  _: readonly
  d3: readonly
  process: readonly
ignorePatterns:
  - build
  - devel
  - dist
overrides:
  - files:
    - webpack.config.js
    - webpack.common.js
    - webpack.dev.js
    - writeHeadersJsonTask.js
    env:
      browser: false
      node: true
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: warn
settings:
  react:
    version: 'detect'
